### PR TITLE
Support 'bazel mod tidy'

### PR DESCRIPTION
**Pull request by mark-thm**
Add support for running `bazel mod tidy`.

### CODE REVIEW

**Review by kevans-theorem — APPROVED** [review]

**Comment by alexeagle** [comment]
It seems like this broke the ability to have only dev_dependency on rules_multitool:

```
ERROR: root_module_direct_deps must be empty if the root module contains no usages with dev_dependency = False
ERROR: error evaluating module extension multitool in @@rules_multitool~//multitool:extension.bzl
```

**Comment by mark-thm** [comment]
@alexeagle does https://github.com/theoremlp/rules_multitool/pull/70 fix this for you?

**Comment by alexeagle** [comment]
@mark-thm yeah thanks, looks good at https://github.com/bazel-contrib/rules_oci/pull/770  (note that I'm doing a naughty lookup of a canonical repo name, which looks like the name is changed in your fix)

**Comment by mark-thm** [comment]
@alexeagle I'm not sure why the canonical repo name would change

**Comment by mark-thm** [comment]
oh I see, it's from an earlier update where we do a repo per tool/arch rather than one per arch.

**Comment by alexeagle** [comment]
sorry I should have been more clear the delta here was from 0.9.0 yes. Thanks!

**Pull request merged**
